---
version: '3.8'
services:
  terraform:
    image: hashicorp/terraform:latest
    environment: 
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    volumes:
      - .:/opt/app:rw
  hello-world:
    build: ./applications/hello-world
    ports:
      - 80:3000
    volumes:
      - ./applications/hello-world:/opt/app/applications/hello-world:rw
